# Generated by Django 4.1.5 on 2023-03-06 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=12)),
                ('titleType', models.CharField(max_length=50)),
                ('primaryTitle', models.CharField(max_length=150)),
                ('originalTitle', models.CharField(max_length=150)),
                ('isAdult', models.BooleanField()),
                ('startYear', models.DateField()),
                ('endYear', models.DateField()),
                ('runtimeMinutes', models.IntegerField()),
                ('genres', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('movies', models.ManyToManyField(to='api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
