# Generated by Django 4.1.5 on 2023-03-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_endyear_alter_movie_startyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtimeMinutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
